Заропс GET для получения ID пользователя
fades-io/auth pull request #5
Opened 2022-02-27 08:27 UTC by ShiryaevNikolay

В рамках данного ПР был реализован GET запрос для получения ID пользователя

2022-03-30 14:44 UTC, igsekor requested changes
Давайте выносить все сообщения в отдельный файл. Отдельный файл для логирования, отдельный — для обработки ошибок.

2022-03-30 14:44 UTC, igsekor commented on internal/database/postgresql/postgresql.go
> +	err := postgres.db.Debug().Table(tokensTable).Model(tokenModel).Where("token = ?", token).Where("token_status = 'Created'").Take(&tokenModel).Error
Это лучше записывать не в одну строчку

2022-03-30 14:44 UTC, igsekor commented on internal/server/routers.go
>  	server.Router.HandlerFunc(http.MethodPost, userLoginURL, middlewares.SetHeadersMiddleware(server.Login))
Кажется, что лучше записывать параметры с новой строки. В данном случае. Надо проверить формирование с помощью `go fmt`.

2022-04-02 09:39 UTC, ShiryaevNikolay commented on internal/database/postgresql/postgresql.go
> +	err := postgres.db.Debug().Table(tokensTable).Model(tokenModel).Where("token = ?", token).Where("token_status = 'Created'").Take(&tokenModel).Error
Исправил

2022-04-02 09:39 UTC, ShiryaevNikolay commented on internal/server/routers.go
>  	server.Router.HandlerFunc(http.MethodPost, userLoginURL, middlewares.SetHeadersMiddleware(server.Login))
Исправил

2022-04-06 12:10 UTC, igsekor requested changes
Всё хорошо. Давайте тогда добавим обработку сигналов от ОС, чтобы уж наверняка быть уверенными в успехе предприятия :)

2022-05-06 18:40 UTC, merged